---
created_at: 2024-12-29
created_by: Vivek
beamformer_config:
  # The total number of beams to be produced (must be a multiple of 32)
  total_nbeams: 512
  # The number of time samples that will be accumulated after detection
  tscrunch: 2
  # The number of frequency channels that will be accumulated after detection
  # Will be coerced to 1 if coherent dedispersion is specified.
  fscrunch: 1
  # The Stokes product to be calculated in the beamformer (I=0, Q=1, U=2, V=3)
  stokes_mode: I
  # Enable CB-IB subtraction in the beamformer
  subtract_ib: True
  # Dispersion measure for coherent dedispersion in pc cm^-3
  # A dispersion plan definition string "
  #           "(<coherent_dm>:<start_incoherent_dm>:"
  #            "<end_incoherent_dm>:<dm_step>:<tscrunch>) or "
  #           "(<coherent_dm>:<tscrunch>) "
  #           "or (<coherent_dm>)")
  #The coherent DMs key below is never used.
  coherent_dms: [0,48,50,52,54,56]

ddplan:
  - "0:0:0:1:1"
  - "48:47:49:0.5:1"
  - "50:49:51:0.5:1"
  - "52:51:53:0.5:1"
  - "54:53:55:0.5:1"
  - "56:55:57:0.5:1"



beam_sets:
  - name: "3HM"
  # full antenna beams at 50% overlap until 3* half mass radii
    antenna_set: ['m000', 'm001', 'm002', 'm003', 'm004', 'm005', 'm006', 'm007',
                  'm008', 'm009', 'm010', 'm011', 'm012', 'm013', 'm014', 'm015',
                  'm016', 'm017', 'm018', 'm019', 'm020', 'm021', 'm022', 'm023',
                  'm024', 'm025', 'm026', 'm027', 'm028', 'm029', 'm030', 'm031',
                  'm032', 'm033', 'm034', 'm035', 'm036', 'm037', 'm038', 'm039',
                  'm040', 'm041', 'm042', 'm043', 'm044', 'm045', 'm046', 'm047',
                  'm048', 'm049', 'm050', 'm051', 'm052', 'm053', 'm054', 'm055',
                  'm057', 'm058', 'm059', 'm060', 'm062', 'm063']

    beams: []

    tilings:
      - nbeams: 47
        reference_frequency: null
        target: "NGC1851,radec,05:14:06.697,-40:02:48.907"
        overlap: 0.5


